name: Build Application

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  # Enable manual triggering for testing
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            output_name: subtitle_translator_macos
            asset_name: subtitle-translator-macos.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[gui]"

    - name: Install build dependencies and clear cache
      run: |
        pip install pyinstaller pytest
        python -m PyInstaller.utils.cli clear-cache

    - name: Run tests
      run: |
        pytest tests/ -v || echo "No tests found or tests failed"

    - name: Create PyInstaller spec file for macOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --windowed --name "${{ matrix.output_name }}" subtitle_translator/gui/main.py



    - name: List build artifacts
      run: ls -R dist

    - name: Package macOS
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        zip -r ../${{ matrix.asset_name }} ${{ matrix.output_name }}.app
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: ${{ matrix.asset_name }}

    - name: Clean up build files
      run: rm -rf build dist

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: macos-latest-build/subtitle-translator-macos.zip
          generate_release_notes: true
