name: Build macOS App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Enable manual triggering for testing

jobs:
  build:
    name: Build macOS App
    runs-on: macos-latest
    env:
      APP_NAME: subtitle_translator_macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip
        ${{ steps.setup-python.outputs.python-path }} -m pip install -e ".[gui]"
        ${{ steps.setup-python.outputs.python-path }} -m pip install pyinstaller

    - name: Build macOS app
      run: |
        QT_PATH=$(${{ steps.setup-python.outputs.python-path }} -c 'import PyQt6; print(PyQt6.__path__[0])')
        ${{ steps.setup-python.outputs.python-path }} -m PyInstaller \
          --windowed \
          --name "${{ env.APP_NAME }}" \
          --add-data "${QT_PATH}:PyQt6" \
          --add-data "${QT_PATH}/Qt6/plugins/platforms:PyQt6/Qt6/plugins/platforms" \
          --add-data "${QT_PATH}/Qt6/plugins/styles:PyQt6/Qt6/plugins/styles" \
          --runtime-hook hook-qt.py \
          --runtime-hook rthook.py \
          --hidden-import PyQt6.QtCore \
          --hidden-import PyQt6.QtGui \
          --hidden-import PyQt6.QtWidgets \
          --hidden-import PyQt6.sip \
          --hidden-import PyQt6.QtDBus \
          --collect-all PyQt6 \
          subtitle_translator/gui/main.py

    - name: Package app
      run: |
        cd dist
        zip -r ../subtitle-translator-macos.zip ${{ env.APP_NAME }}.app
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: subtitle-translator-macos.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: subtitle-translator-macos.zip
        generate_release_notes: true
